index:
   path: /
   controller: App\Controller\ArticleController::homepage

dashboard:
   path: /eadmin
   controller: App\Controller\Admin\DashboardController::index

app_logout:
   path: /logout
   methods: GET
